packages:
  - 'apps/*'
  - 'packages/*'
  - 'services/*'

catalog:
  '@eslint/js': 9.19.0
  '@types/cors': 2.8.17
  '@types/express': 5.0.0
  '@types/jsonwebtoken': 9.0.8
  '@types/node': 22.13.0
  cors: 2.8.5
  eslint: 9.19.0
  express: 4.21.2
  globals: 15.14.0
  jsonwebtoken: 9.0.2
  jwt-decode: 4.0.0
  prettier: 3.4.2
  socket.io: 4.8.1
  socket.io-client: 4.8.1
  surrealdb: 1.1.0
  tsx: 4.19.2
  typescript: 5.7.3
  typescript-eslint: 8.22.0
  vue-i18n: 11.1.0
  zod: 3.24.1
